export const STATUS_CODES = {
    // Success codes
    OK: 200,
    CREATED: 201,
    NO_CONTENT: 204,
  
    // Client error codes
    BAD_REQUEST: 400,
    UNAUTHORIZED: 401,
    FORBIDDEN: 403,
    NOT_FOUND: 404,
    METHOD_NOT_ALLOWED: 405,
    REQUEST_TIMEOUT: 408,
    CONFLICT: 409,
    UNPROCESSABLE_ENTITY: 422,
    TOO_MANY_REQUESTS: 429,
  
    // Server error codes
    INTERNAL_SERVER_ERROR: 500,
    BAD_GATEWAY: 502,
    SERVICE_UNAVAILABLE: 503,
    GATEWAY_TIMEOUT: 504,
  };
  
  // Axios specific error codes
  export const AXIOS_ERROR_CODES = {
    NETWORK_ERROR: "ERR_NETWORK",
    TIMEOUT: "ECONNABORTED",
    CANCELED: "ERR_CANCELED",
    CONNECTION_REFUSED: "ECONNREFUSED",
    NOT_FOUND: "ENOTFOUND",
    BAD_REQUEST: "ERR_BAD_REQUEST",
    BAD_RESPONSE: "ERR_BAD_RESPONSE",
  };
  
  // Error types for UI handling
  export const ERROR_TYPES = {
    NETWORK_ERROR: "NETWORK_ERROR",
    SERVER_DOWN: "SERVER_DOWN",
    DNS_ERROR: "DNS_ERROR",
    TIMEOUT_ERROR: "TIMEOUT_ERROR",
    BACKEND_ERROR: "BACKEND_ERROR",
    UNKNOWN_ERROR: "UNKNOWN_ERROR",
  };